name: Build Wheels

on: [push, pull_request]

jobs:
  wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      name: Install Python
      with:
        python-version: '3.11'
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==2.13.0
    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir dist
    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/

  release:
    permissions:
      contents: write  # for actions/create-release
    name: Create GitHub Release
    needs: [wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Tag Version
        id: set_tag
        run: |
          export V=$(python -c "print(next(iter(eval(L.split('=')[-1]) for L in open('pyproject.toml') if 'version' in L)))")
          echo "::set-output name=tag_name::${V}"
      - uses: actions/download-artifact@v3
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.set_tag.outputs.tag_name }}
          artifacts: "*.whl"